# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e79801ffbb21fa208f1dd47e09633bd9046300228b503b7eff3a4aeadc116c10fec403e5631d12ca28d774ce368119ffeb5fa89df8ea83c8f2050d3c5a506093

test:
  secret_key_base: 7a56c6e419e22626d95df425398fa4b9659734788d3beefc343d0001799b82388bc3e662c600eeff57349ab4a0966de48ca157108eaa90a5cec21a5e549d530f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
